/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.semanticwb.ontologyengineering;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.semanticwb.ontologyengineering.ontologysearch.LOVSearch;
import org.semanticwb.ontologyengineering.ontologysearch.SearchConfiguration;
import org.semanticwb.ontologyengineering.ontologysearch.WatsonSearch;

/**
 *
 * @author vieyra
 */
public class GUISearch extends javax.swing.JFrame {

   /**
    * Creates new form GUISearch
    */
   public GUISearch() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      terms = new javax.swing.JTextArea();
      lovRadioButton = new javax.swing.JRadioButton();
      swoogleRadioButton = new javax.swing.JRadioButton();
      watsonRadioButton = new javax.swing.JRadioButton();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      classesRadioButton = new javax.swing.JRadioButton();
      propertiesRadioButton = new javax.swing.JRadioButton();
      individualsRadioButton = new javax.swing.JRadioButton();
      jLabel3 = new javax.swing.JLabel();
      localnameRadioButton = new javax.swing.JRadioButton();
      labelRadioButton = new javax.swing.JRadioButton();
      commentRadioButton = new javax.swing.JRadioButton();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      exactmatchRadioButton = new javax.swing.JRadioButton();
      tokenmatchRadioButton = new javax.swing.JRadioButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Search ontologies");

      terms.setColumns(20);
      terms.setRows(5);
      jScrollPane1.setViewportView(terms);

      lovRadioButton.setSelected(true);
      lovRadioButton.setText("LOV");
      lovRadioButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            lovRadioButtonActionPerformed(evt);
         }
      });

      swoogleRadioButton.setText("Swoogle");
      swoogleRadioButton.setEnabled(false);
      swoogleRadioButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            swoogleRadioButtonActionPerformed(evt);
         }
      });

      watsonRadioButton.setSelected(true);
      watsonRadioButton.setText("Watson");
      watsonRadioButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            watsonRadioButtonActionPerformed(evt);
         }
      });

      jLabel1.setText("Search services:");

      jLabel2.setText("Entities:");

      classesRadioButton.setSelected(true);
      classesRadioButton.setText("Classes");
      classesRadioButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            classesRadioButtonActionPerformed(evt);
         }
      });

      propertiesRadioButton.setText("Properties");
      propertiesRadioButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            propertiesRadioButtonActionPerformed(evt);
         }
      });

      individualsRadioButton.setText("Individuals");
      individualsRadioButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            individualsRadioButtonActionPerformed(evt);
         }
      });

      jLabel3.setText("Scope:");

      localnameRadioButton.setSelected(true);
      localnameRadioButton.setText("Local name");
      localnameRadioButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            localnameRadioButtonActionPerformed(evt);
         }
      });

      labelRadioButton.setSelected(true);
      labelRadioButton.setText("label");
      labelRadioButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            labelRadioButtonActionPerformed(evt);
         }
      });

      commentRadioButton.setText("Comment");
      commentRadioButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            commentRadioButtonActionPerformed(evt);
         }
      });

      jButton1.setText("Search");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      jButton2.setText("Reset");
      jButton2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
         }
      });

      jLabel4.setText("Type the terms to search, separated by quotes");

      jLabel5.setText("Match:");

      exactmatchRadioButton.setSelected(true);
      exactmatchRadioButton.setText("Exact match");
      exactmatchRadioButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            exactmatchRadioButtonActionPerformed(evt);
         }
      });

      tokenmatchRadioButton.setText("Token match");
      tokenmatchRadioButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            tokenmatchRadioButtonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel1)
                     .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(lovRadioButton)
                           .addComponent(watsonRadioButton)
                           .addComponent(swoogleRadioButton))))
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(individualsRadioButton)
                     .addComponent(propertiesRadioButton)
                     .addComponent(classesRadioButton)
                     .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)))
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3))
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(localnameRadioButton)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(labelRadioButton)
                              .addComponent(commentRadioButton))
                           .addGap(11, 11, 11))))
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5))
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(exactmatchRadioButton)
                        .addComponent(tokenmatchRadioButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jButton1))))
            .addContainerGap())
         .addGroup(layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addComponent(jLabel4)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                     .addComponent(jLabel1)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(lovRadioButton)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(watsonRadioButton)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(swoogleRadioButton))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                     .addComponent(jLabel2)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(classesRadioButton)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(propertiesRadioButton)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(individualsRadioButton))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                     .addComponent(jLabel3)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                           .addComponent(localnameRadioButton)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                           .addComponent(labelRadioButton)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                           .addComponent(commentRadioButton))
                        .addGroup(layout.createSequentialGroup()
                           .addComponent(jButton1)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                           .addComponent(jButton2)))))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel5)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(exactmatchRadioButton)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(tokenmatchRadioButton)))
            .addGap(29, 29, 29))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void lovRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lovRadioButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_lovRadioButtonActionPerformed

   private void swoogleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swoogleRadioButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_swoogleRadioButtonActionPerformed

   private void watsonRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watsonRadioButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_watsonRadioButtonActionPerformed

   private void classesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classesRadioButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_classesRadioButtonActionPerformed

   private void propertiesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertiesRadioButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_propertiesRadioButtonActionPerformed

   private void individualsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_individualsRadioButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_individualsRadioButtonActionPerformed

   private void localnameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localnameRadioButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_localnameRadioButtonActionPerformed

   private void labelRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelRadioButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_labelRadioButtonActionPerformed

   private void commentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentRadioButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_commentRadioButtonActionPerformed

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      terms.setText("");
      
      //search engines
      swoogleRadioButton.setSelected(true);
      lovRadioButton.setSelected(true);
      
      //entities
      classesRadioButton.setSelected(true);
      propertiesRadioButton.setSelected(false);
      individualsRadioButton.setSelected(false);
      
      //scope
      localnameRadioButton.setSelected(true);
      labelRadioButton.setSelected(true);
      commentRadioButton.setSelected(false);
      
      //match
      exactmatchRadioButton.setSelected(true);
      tokenmatchRadioButton.setSelected(false);
      
   }//GEN-LAST:event_jButton2ActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      //get the list of terms to search
      List<String> termsSearched = new ArrayList<String>();
      for (String term : terms.getText().replace("\n", " ").replace("\t", " ").split(",")) {
         term = term.trim();
         if(!termsSearched.contains(term)){
            termsSearched.add(term);
         }
      }
      
      //Set the configurations
      SearchConfiguration conf = new SearchConfiguration();
      
      //Setting entities
      conf.setClasses(classesRadioButton.isSelected());
      conf.setProperties(propertiesRadioButton.isSelected());
      conf.setIndividuals(individualsRadioButton.isSelected());
      
      //setting scopes
      conf.setLocalName(localnameRadioButton.isSelected());
      conf.setLabel(labelRadioButton.isSelected());
      conf.setComment(commentRadioButton.isSelected());
      
      //setting matches
      if(exactmatchRadioButton.isSelected()){
         conf.setExactMatch(true);
      } else {
         conf.setTokenMatch(true);
         conf.setExactMatch(false);
      }
      try {
         List<String[]> retrievedResources = new ArrayList<String[]>();
         if (lovRadioButton.isSelected()) {
            LOVSearch lovSearch = new LOVSearch(conf);
            retrievedResources.addAll(lovSearch.searchEntities(termsSearched.toArray(new String[]{})));
         } 
         if(watsonRadioButton.isSelected()){
            WatsonSearch wSearch = new WatsonSearch(conf);
            retrievedResources.addAll(wSearch.searchTerms(termsSearched.toArray(new String[]{})));
         }
         if (!(lovRadioButton.isSelected() || swoogleRadioButton.isSelected())) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select at least one service!");
         }
         for (String[] resource : retrievedResources) {
            System.out.println(resource[0] + "\t" + resource[1] + "\t" + resource[2]);
         }
         new ResultantResources(retrievedResources).setVisible(true);
         this.dispose();
      } catch (IOException ex) {
         javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
      }
      
   }//GEN-LAST:event_jButton1ActionPerformed

   private void exactmatchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exactmatchRadioButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_exactmatchRadioButtonActionPerformed

   private void tokenmatchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokenmatchRadioButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_tokenmatchRadioButtonActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(GUISearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(GUISearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(GUISearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(GUISearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new GUISearch().setVisible(true);
         }
      });
   }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JRadioButton classesRadioButton;
   private javax.swing.JRadioButton commentRadioButton;
   private javax.swing.JRadioButton exactmatchRadioButton;
   private javax.swing.JRadioButton individualsRadioButton;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JRadioButton labelRadioButton;
   private javax.swing.JRadioButton localnameRadioButton;
   private javax.swing.JRadioButton lovRadioButton;
   private javax.swing.JRadioButton propertiesRadioButton;
   private javax.swing.JRadioButton swoogleRadioButton;
   private javax.swing.JTextArea terms;
   private javax.swing.JRadioButton tokenmatchRadioButton;
   private javax.swing.JRadioButton watsonRadioButton;
   // End of variables declaration//GEN-END:variables
}
